services:
  kafka_controller:
    image: bitnami/kafka:3.9.0
    container_name: kraft-kafka-1
    ports:
      # - 9092:9092
      # - 9093:9093
      - 9093:9093
    environment:
      # KAFKA_BROKER_ID: 1
      KAFKA_KRAFT_CLUSTER_ID: q1Sh-9_ISia_zwGINzRvyQ
      KAFKA_CFG_LISTENERS: CONTROLLER://:9093
      # KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kraft-kafka-1:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka_controller:9093
      KAFKA_CFG_PROCESS_ROLES: controller
      KAFKA_CFG_NODE_ID: 1
      # KAFKA_LOG_DIRS: /var/lib/kafka/data
      # KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      # KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: true
      # KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    # volumes:
    # - ./kafka-data:/var/lib/kafka/data
    networks:
      - kafka-net
  kafka_broker_1:
    image: bitnami/kafka:3.9.0
    container_name: kraft-kafka-2
    ports:
      - 9094:9094
    depends_on:
      - kafka_controller
    environment:
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_KRAFT_CLUSTER_ID: q1Sh-9_ISia_zwGINzRvyQ
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_NUM_PARTITIONS: 3
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9094
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker_1:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka_controller:9093
      KAFKA_CFG_PROCESS_ROLES: broker
      KAFKA_CFG_NODE_ID: 2
      # KAFKA_LOG_DIRS: /var/lib/kafka/data
      # KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      # KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: true
      # KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    # volumes:
    # - ./kafka-data:/var/lib/kafka/data
    networks:
      - kafka-net
  kafka_broker_2:
    image: bitnami/kafka:3.9.0
    container_name: kraft-kafka-3
    ports:
      - 9095:9095
    depends_on:
      - kafka_controller
    environment:
      KAFKA_KRAFT_CLUSTER_ID: q1Sh-9_ISia_zwGINzRvyQ
      KAFKA_BROKER_ID: 3
      KAFKA_CFG_NUM_PARTITIONS: 3
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9095
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker_2:9092,EXTERNAL://localhost:9095
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka_controller:9093
      KAFKA_CFG_PROCESS_ROLES: broker
      KAFKA_CFG_NODE_ID: 3
      # KAFKA_LOG_DIRS: /var/lib/kafka/data
      # KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      # KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: true
      # KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    # volumes:
    # - ./kafka-data:/var/lib/kafka/data
    networks:
      - kafka-net
  kafka_broker_3:
    image: bitnami/kafka:3.9.0
    container_name: kraft-kafka-4
    ports:
      - 9096:9096
    depends_on:
      - kafka_controller
    environment:
      KAFKA_KRAFT_CLUSTER_ID: q1Sh-9_ISia_zwGINzRvyQ
      KAFKA_BROKER_ID: 4
      KAFKA_CFG_NUM_PARTITIONS: 3
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9096
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker_3:9092,EXTERNAL://localhost:9096
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka_controller:9093
      KAFKA_CFG_PROCESS_ROLES: broker
      KAFKA_CFG_NODE_ID: 4
      # KAFKA_LOG_DIRS: /var/lib/kafka/data
      # KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      # KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: true
      # KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    # volumes:
    # - ./kafka-data:/var/lib/kafka/data
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
